version: "3.8"

services:
  app:
    image: wordpress:php8.3-apache
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - app_data:/var/www/html
    networks:
      app_db:
      proxy_apps:
    depends_on:
      - db

  db:
    image: percona/percona-server:8.3
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      app_db:

volumes:
  app_data:
  db_data:

networks:
  app_db:
  proxy_apps:
    name: proxy_apps
    external: true