version: "3.8"

services:
  app:
    image: wordpress:php8.3-fpm-alpine
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - app_data:/var/www/html
    networks:
      app_db:
      app_web:
    depends_on:
      - db

  web:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - app_data:/var/www/html
      - $PWD/conf:/etc/nginx/conf.d:ro
    networks:
      app_web:
      proxy_apps:
    depends_on:
      - app

  db:
    image: mariadb:11.4-rc
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=wordpress
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD=wordpress
    labels:
      - ofelia.restart=true
      - ofelia.enabled=true
      - "ofelia.job-exec.${COMPOSE_PROJECT_NAME}dbbackup.schedule=0 0 1 * * *"
      - "ofelia.job-exec.${COMPOSE_PROJECT_NAME}dbbackup.command=sh -c 'mariadb-dump --user=wordpress --password=wordpress wordpress > /var/lib/mysql/backup.sql'"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      app_db:

volumes:
  app_data:
  db_data:

networks:
  app_db:
  app_web:
  proxy_apps:
    name: proxy_apps
    external: true