services:
  app:
    image: ghcr.io/hueske-digital/wordpress:latest
    user: "1000:1000"
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - WORDPRESS_DB_HOST=${DB_HOST:-db}
      - WORDPRESS_DB_USER=${DB_USER:-wordpress}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD:-wordpress}
      - WORDPRESS_DB_NAME=${DB_NAME:-wordpress}
      - PHP_FPM_PM_MODE=${PHP_FPM_PM_MODE:-dynamic}
      - PHP_FPM_PM_MAX_CHILDREN=${PHP_FPM_PM_MAX_CHILDREN:-5}
      - PHP_FPM_PM_START_SERVERS=${PHP_FPM_PM_START_SERVERS:-2}
      - PHP_FPM_PM_MIN_SPARE_SERVERS=${PHP_FPM_PM_MIN_SPARE_SERVERS:-1}
      - PHP_FPM_PM_MAX_SPARE_SERVERS=${PHP_FPM_PM_MAX_SPARE_SERVERS:-3}
      - PHP_FPM_PM_MAX_REQUESTS=${PHP_FPM_PM_MAX_REQUESTS:-200}
    labels:
      - ofelia.restart=true
      - ofelia.enabled=true
      - "ofelia.job-exec.${COMPOSE_PROJECT_NAME}cron.schedule=${WORDPRESS_CRON_SCHEDULE:-0 */5 * * * *}"
      - "ofelia.job-exec.${COMPOSE_PROJECT_NAME}cron.command=sh -c 'php wp-cron.php'"
    volumes:
      - $PWD/data/web:/var/www/html
      - $PWD/conf/php/custom.ini:/usr/local/etc/php/conf.d/90-custom.ini
      - $PWD/conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      app_db:
      app_web:
    depends_on:
      - db

  web:
    image: nginx:stable-alpine
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - COMPOSE_PROJECT_NAME
    volumes:
      - $PWD/data/web:/var/www/html
      - $PWD/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/conf/nginx/7g.conf:/etc/nginx/conf.d/7g.conf
      - $PWD/conf/nginx/7g-firewall.conf:/etc/nginx/conf.d/7g-firewall.conf
      - $PWD/conf/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    networks:
      app_web:
      proxy_apps:
    depends_on:
      - app

  db:
    image: mariadb:${MARIADB_VERSION:-11.4}
    restart: unless-stopped
    command: mariadbd --innodb-buffer-pool-size=${MARIADB_INNODB_BUFFER_SIZE:-128M} --max-connections=${MARIADB_MAX_CONNECTIONS:-150} --tmp-table-size=${MARIADB_TMP_TABLE_SIZE:-16M} --max-heap-table-size=${MARIADB_MAX_HEAP_TABLE_SIZE:-16M}
    environment:
      - TZ=Europe/Berlin
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-wordpress}
      - MARIADB_DATABASE=${DB_NAME:-wordpress}
      - MARIADB_USER=${DB_USER:-wordpress}
      - MARIADB_PASSWORD=${DB_PASSWORD:-wordpress}
      - MARIADB_AUTO_UPGRADE=1
    labels:
      - ofelia.restart=true
      - ofelia.enabled=true
      - "ofelia.job-exec.${COMPOSE_PROJECT_NAME}dbbackup.schedule=${BACKUP_CRON_SCHEDULE:-0 0 3 * * *}"
      - "ofelia.job-exec.${COMPOSE_PROJECT_NAME}dbbackup.command=sh -c 'mariadb-dump --user=${DB_USER:-wordpress} --password=${DB_PASSWORD:-wordpress} ${DB_NAME:-wordpress} > /docker-entrypoint-initdb.d/backup.sql'"
    volumes:
      - $PWD/data/db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      app_db:

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      app_db:
      proxy_apps:
    profiles:
      - adminer

volumes:
  db_data:

networks:
  app_db:
  app_web:
  proxy_apps:
    name: proxy_apps
    external: true
