version: "3.8"

services:
  app:
    image: wordpress:php8.3-fpm-alpine
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - app_data:/var/www/html
    networks:
      app_db:
      app_web:
    depends_on:
      - db

  web:
    image: nginx:1-alpine
    restart: unless-stopped
    volumes:
      - app_data:/var/www/html
      - $PWD/build/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      app_web:
      proxy_apps:
    depends_on:
      - app

  db:
    image: mysql:8.3
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      app_db:

volumes:
  app_data:
  db_data:

networks:
  app_db:
  app_web:
  proxy_apps:
    name: proxy_apps
    external: true