name: Build and Push Docker image

env:
  PHP_VERSION: 8.3

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull the necessary images
        run: |
          docker pull wordpress:php${{ env.PHP_VERSION }}-fpm-alpine
          docker pull ghcr.io/hueske-digital/wordpress:latest

      - name: Get the last layer ID of the base image
        id: base_image
        run: |
          ALL_LAYERS=$(docker inspect wordpress:php8.3-fpm-alpine --format='{{range .RootFS.Layers}}{{.}} {{end}}')
          BASE_IMAGE_LAST_LAYER=$(echo $ALL_LAYERS | awk '{print $NF}')
          echo "BASE_IMAGE_LAST_LAYER=$BASE_IMAGE_LAST_LAYER" >> $GITHUB_ENV

      - name: Get all layers of your custom image
        run: |
          CUSTOM_IMAGE_LAYERS=$(docker inspect ghcr.io/hueske-digital/wordpress:latest --format='{{range .RootFS.Layers}}{{.}}{{"\n"}}{{end}}' || echo "none")
          echo "CUSTOM_IMAGE_LAYERS=$CUSTOM_IMAGE_LAYERS" >> $GITHUB_ENV

      - name: Check if the base image last layer is in the custom image layers
        run: |
          if echo "$CUSTOM_IMAGE_LAYERS" | grep -q "$BASE_IMAGE_LAST_LAYER"; then
            echo "The base layer is present in the custom image."
            echo "base_layer_changed=false" >> $GITHUB_ENV
          else
            echo "The base layer is not present in the custom image."
            echo "base_layer_changed=true" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        if: env.base_layer_changed == 'true'
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./build
          tags: ghcr.io/hueske-digital/wordpress:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            PHP_VERSION=${{ env.PHP_VERSION }}

      - name: Do not automatically disable workflow execution
        uses: gautamkrishnar/keepalive-workflow@v1